### ISSUE TITLE
I am having trouble using any of the media query modifiers

### ISSUE THREAD

**Issue by danhollick** [jamesmcallister/styled-components-tachyons#12]
The modifiers `_ns , _m, _l` don't seem to work and I am not sure why.
Do they need to be added in the variables.css file somehow?

**Comment by jamesmcallister** [comment]
make sure you have this follow defined in your global css

 ```css
 :root {
--spacing-none: 0;
  --spacing-extra-small: .25rem;
  --spacing-small: .5rem;
  --spacing-medium: 1rem;
  --spacing-large: 2rem;
  --spacing-extra-large: 4rem;
  --spacing-extra-extra-large: 8rem;
  --spacing-extra-extra-extra-large: 16rem;
}
```

Me know how you get on.
